// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace gsumath.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230113100732_selam")]
    partial class selam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("gsu_math.Models.Bilgi", b =>
                {
                    b.Property<int>("BilgiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Başlık")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tür")
                        .HasColumnType("TEXT");

                    b.HasKey("BilgiId");

                    b.ToTable("Bilgi");
                });

            modelBuilder.Entity("gsu_math.Models.Duyuru", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metin")
                        .HasColumnType("TEXT");

                    b.HasKey("DuyuruId");

                    b.ToTable("Duyuru");
                });

            modelBuilder.Entity("gsu_math.Models.Etkinlik", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("atCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EtkinlikId");

                    b.ToTable("Etkinlik");
                });

            modelBuilder.Entity("gsu_math.Models.ForumBaslik", b =>
                {
                    b.Property<int>("ForumBaslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("begenisayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cevapsayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("creater")
                        .HasColumnType("TEXT");

                    b.Property<string>("slug")
                        .HasColumnType("TEXT");

                    b.HasKey("ForumBaslikId");

                    b.ToTable("ForumBaslik");
                });

            modelBuilder.Entity("gsu_math.Models.ForumCevap", b =>
                {
                    b.Property<int>("ForumCevapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BegeniSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForumBaslikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("at_created")
                        .HasColumnType("TEXT");

                    b.Property<string>("faydalibulanlar")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("ForumCevapId");

                    b.ToTable("ForumCevap");
                });

            modelBuilder.Entity("gsu_math.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmPwd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForumCevapId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_mail_validated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_validate")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("ForumCevapId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("gsu_math.Models.User", b =>
                {
                    b.HasOne("gsu_math.Models.ForumCevap", null)
                        .WithMany("users")
                        .HasForeignKey("ForumCevapId");
                });

            modelBuilder.Entity("gsu_math.Models.ForumCevap", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
